import React, { useEffect, useState } from 'react'

const defaults = { title:'', date:'2026-09-07', start:'09:00', duration:60, type:'meeting', color:'blue' }
export function EventModal({ event, onSave, onDelete, onClose }) {
  const [form, setForm] = useState(event || defaults)
  useEffect(()=>setForm(event || defaults), [event])
  const update = (name, value) => setForm(f=>({...f,[name]:value}))
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget) onClose()}}><form className="modal" onSubmit={e=>{e.preventDefault(); onSave({...form,duration:Number(form.duration)})}}><div className="modal-title"><div><span>CALENDAR EVENT</span><h2>{event ? 'Edit scheduled post' : 'Create scheduled post'}</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></div><label>Title<input autoFocus value={form.title} onChange={e=>update('title',e.target.value)} placeholder="e.g. Product launch" required /></label><div className="form-grid"><label>Date<input type="date" value={form.date} onChange={e=>update('date',e.target.value)} required /></label><label>Start time<input type="time" value={form.start} onChange={e=>update('start',e.target.value)} required /></label></div><div className="form-grid"><label>Duration<select value={form.duration} onChange={e=>update('duration',e.target.value)}><option value="30">30 minutes</option><option value="60">1 hour</option><option value="90">1.5 hours</option><option value="120">2 hours</option></select></label><label>Type<select value={form.type} onChange={e=>{const type=e.target.value; update('type',type); update('color',{meeting:'blue',deadline:'red',focus:'green',personal:'amber'}[type])}}><option value="meeting">Meeting</option><option value="deadline">Deadline</option><option value="focus">Focus block</option><option value="personal">Personal</option></select></label></div><div className="modal-actions">{event && <button type="button" className="danger" onClick={()=>onDelete(event.id)}>Delete</button>}<span/><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Save post</button></div></form></div>
}
